### ISSUE TITLE
[Metrics CLI] Design the Sentry configuration process

### ISSUE THREAD

**Issue by solid-vovabeloded** [platform-platform/monorepo#1098]
**Description**

Create a design that will explain the Sentry configuration process during the Metrics application deployment.

**Acceptance Criteria**
- [ ] Design explaining the process of Sentry configuration in terms of Metrics CLI

**Additional context**
[Sentry Command Line Interface](https://docs.sentry.io/product/cli/)

**Comment by illia-romanenko** [comment]
closed in #1182
