### ISSUE TITLE
Add FPS monitor

### ISSUE THREAD

**Issue by bootstraponline** [platform-platform/monorepo#161]
**Author the user story for this feature**
As a developer, I want to be able to analyze performance (FPS) so I can make changes in configuration/implementation to improve performance. 

**Is your feature request related to a problem? Please describe.**
There are a couple of ways of configuring deployments so we need to be able to have an ability to compare them using the data.

**Describe the solution you'd like**
Integrate statsfl plugin to the app. Choose how to toggle it (ON/OFF).

**Describe alternatives you've considered**
- performance_fps
- flutter_fps

Both have lower popularity/usage and can be considered as an alternative if there are any hard issues with statsfl.

**Additional context**
https://blog.gskinner.com/archives/2020/04/flutter-introducing-statsfl-an-fps-monitor-for-flutter.html

**Comment by solid-maxim** [comment]
The statsfl plugin works well on the beta channel, but currently, our flutter version is 1.15.3, and I've faced some rendering issues with that plugin.

Alternatives:
- performance_fps is not working on the web.
- flutter_fps crashed with errors.

So to resolve this issue we need to wait to upgrade flutter version.
