### ISSUE TITLE
Setup Sentry

### ISSUE THREAD

**Issue by bootstraponline** [platform-platform/monorepo#162]
[flutter_crashlytics](https://pub.dev/packages/flutter_crashlytics) doesn't support Flutter Web. Let's look into [sentry-dart](https://github.com/getsentry/sentry-dart) instead.

The goal is to report in the dashboard to sentry so we can have a dashboard to understand how the deployments are performing.

**Comment by illia-romanenko** [comment]
It seems to be not supported as of now https://github.com/FirebaseExtended/flutterfire/issues/1693 and status is tracked here: https://github.com/firebase/firebase-js-sdk/issues/710

**Comment by illia-romanenko** [comment]
@bootstraponline should we close this for now or we need to search for alternatives?

**Comment by bootstraponline** [comment]
let's close for now. thanks for checking!

**Comment by bootstraponline** [comment]
I think we should look into Sentry.

https://github.com/getsentry/sentry-dart
