### ISSUE TITLE
[ci_integrations] improve error messages & investigate firebase_dart_sdk

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#193]
1. When user specified wrong credentials in the config - it produces Exception 400 - Bad request - we should try to see if we can get more understandable error
2. Look for firedart alternative to see if we can use it (if that makes sense) https://github.com/fluttercommunity/firebase_dart_sdk

**Comment by solid-vladlaba** [comment]
platform-platform/firedart#5
