### ISSUE TITLE
Import Circle CI data to Firestore

### ISSUE THREAD

**Issue by bootstraponline** [platform-platform/monorepo#21]
Develop a program that uses the Circle CI API to import all builds for a given job to Firebase. This should be idempotent. The program will run on a schedule and constantly update Firestore with the latest builds.

Name | Description
| --- | --- |
buildId | unique identifier of the build
buildDate | date the build was started
buildQueued | the amount of time the build spent waiting to execute
buildDuration | the amount of time the build took to execute (does not include queue time)
buildSuccessful | boolean for if the build was successful or not

**Comment by illia-romanenko** [comment]
Should this be a part of Guardian Service?

**Comment by bootstraponline** [comment]
I think for now I want to keep Guardian and build metrics separate.

Build metrics is only for build data.
Guardian is only for test data.

A minimal implementation of this would be a metrics CLI that knows how to grab Circle CI data and import to Firebase. That same CLI would also know how to fetch data from other build services such as buildkite.

**Comment by bootstraponline** [comment]
Decided not to support Circle CI.
