### ISSUE TITLE
Implement Flaky Test detection algorithm

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#42]
As we get detailed Flaky Test detection algorithm in #41 we want to implement a Flaky Test detection algorithm according to specification.

**Comment by bootstraponline** [comment]
A flaky test is a test that in the last 3 runs, did not produce the same result. Only look at the last 3 test executions.

Examples

1) ✅ ❌ ✅ = Flaky
2) ✅ ✅ ✅ = Stable
3) ❌ ❌ ❌ = Stable
