### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#485]
**Author the user story for this feature**

As a user, I want to make sure that Unicode characters are fully supported so I can name my projects and project groups using Unicode characters.

**Is your feature request related to a problem? Please describe.**
We want to make sure when user types in Unicode characters there are no issues with it while using the project.

**Describe the solution you'd like**
Find and fix any Unicode related issues.

**Describe alternatives you've considered**
None as Unicode as a de-facto standard for all user typed texts.

**Additional context**

User fields:
- Project name
- Project group name

Areas:
- Dashboard
- Project groups page

**Comment by solid-daniyilyevtyushkin** [comment]
# Our research has shown, that Project names and Project Group names support Unicode characters.

## 1. Project names

### We can create a Project with Unicode and special characters in its name:
<img width="1192" alt="Снимок экрана 2020-09-09 в 10 18 12" src="https://user-images.githubusercontent.com/69351065/92568224-88ed9600-f287-11ea-8d73-4ff421e07759.png">
<img width="1356" alt="Снимок экрана 2020-09-09 в 10 22 27" src="https://user-images.githubusercontent.com/69351065/92568241-8ee37700-f287-11ea-96fe-41c8658ccf15.png">

### We can use these characters as a Project Name Filter:
<img width="1208" alt="Снимок экрана 2020-09-09 в 10 18 20" src="https://user-images.githubusercontent.com/69351065/92568409-cbaf6e00-f287-11ea-9c82-2c1611115a13.png">
<img width="1209" alt="Снимок экрана 2020-09-09 в 10 18 42" src="https://user-images.githubusercontent.com/69351065/92568424-cf42f500-f287-11ea-89a1-b4e43fa57630.png">
<img width="1341" alt="Снимок экрана 2020-09-09 в 10 22 44" src="https://user-images.githubusercontent.com/69351065/92568472-ea156980-f287-11ea-846f-4e8f5544da7d.png">


## 2. Project Group names

### We can create a Project Group with Unicode characters and special symbols:
<img width="481" alt="Снимок экрана 2020-09-09 в 10 19 55" src="https://user-images.githubusercontent.com/69351065/92568834-6b6cfc00-f288-11ea-8ebe-7af6d7d400b5.png">

### We can use these Project Group Names in a Project Group dropdown for filtering by Project Group:
<img width="238" alt="Снимок экрана 2020-09-09 в 10 39 08" src="https://user-images.githubusercontent.com/69351065/92569025-b38c1e80-f288-11ea-91a6-ad9883315839.png">
<img width="1283" alt="Снимок экрана 2020-09-09 в 10 20 50" src="https://user-images.githubusercontent.com/69351065/92568845-70ca4680-f288-11ea-99b6-ec1eec8888fc.png">

### Project Group dialogs support Project Group Names with Unicode characters and special symbols:
<img width="485" alt="Снимок экрана 2020-09-09 в 10 45 35" src="https://user-images.githubusercontent.com/69351065/92569684-99067500-f289-11ea-99b8-e2fa72e9f0b1.png">
<img width="475" alt="Снимок экрана 2020-09-09 в 10 45 48" src="https://user-images.githubusercontent.com/69351065/92569721-a0c61980-f289-11ea-836c-39e540614173.png">

### Toasts support Project Group Names with Unicode characters and special symbols:
<img width="760" alt="Снимок экрана 2020-09-09 в 10 42 12" src="https://user-images.githubusercontent.com/69351065/92569303-1f6e8700-f289-11ea-9614-4f580c773aa7.png">
