### ISSUE TITLE
Introduce the light theme to the Dashboard page

### ISSUE THREAD

**Issue by solid-vladlaba** [platform-platform/monorepo#525]
**Author the user story for this feature**

As a user, I want to have the Dashboard page match the light theme so I can be more comfortable using the app.

**Is your feature request related to a problem? Please describe.**
It's related to designs.

**Describe the solution you'd like**
Add relevant light theme configurations for the Dashboard page and make sure that it matches the designs.

**Describe alternatives you've considered**
Project specification requirement.

**Additional context**
No additional context.

**Comment by illia-romanenko** [comment]
Text font size on the dashboard page in the light theme is different from Zeplin/Dark theme.
