### ISSUE TITLE
Evaluate SKIA support after Flutter upgrade

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#589]
**Author the user story for this feature**

As a developer, I want to understand the state of SKIA support so I can decide that SKIA makes sense/any issues need to be fixed.

**Comment by vova-beloded** [comment]
There is an issue with images and fonts when using the SKIA renderer. I've created a [#605](https://github.com/platform-platform/monorepo/issues/605) and [#604](https://github.com/platform-platform/monorepo/issues/604) issues to investigate the approaches of solving them.
