### ISSUE TITLE
Investigate SKIA images loading issue

### ISSUE THREAD

**Issue by solid-vovabeloded** [platform-platform/monorepo#604]
**Author the user story for this feature**

As a developer, I want to understand the SKIA renderer images problem so I can find ways of fixing it.

**Is your feature request related to a problem? Please describe.**

When running the Metrics application using the SKIA renderer, the images do not load.

**Describe the solution you'd like**

We should find the reason for images do not load in the SKIA renderer. 

**Describe alternatives you've considered**

No alternatives are considered.

**Additional context**

No additional context.

**Comment by illia-romanenko** [comment]
We can try a workaround to load images suggested in the linked Flutter issue.
