### ISSUE TITLE
Investigate the SKIA fonts problem

### ISSUE THREAD

**Issue by solid-vovabeloded** [platform-platform/monorepo#605]
**Author the user story for this feature**

As a developer, I want to understand the SKIA renderer fonts problem so I can find ways of fixing it.

**Is your feature request related to a problem? Please describe.**

When running the Metrics application using the SKIA renderer, the wrong fonts used (the used fonts looks like the default one). 

**Describe the solution you'd like**

We should find the reason for why the fonts are different from the given one.

**Describe alternatives you've considered**

No alternatives are considered.

**Additional context**

No additional context.

**Comment by illia-romanenko** [comment]
Fixed in the newer flutter version - Flutter upgrade is required.

**Comment by illia-romanenko** [comment]
Close in favor of #779
