### ISSUE TITLE
Firebase remote config

### ISSUE THREAD

**Issue by bootstraponline** [platform-platform/monorepo#618]
**Author the user story for this feature**

As a developer, I want to control the features enabled on metrics so I can customize the app experience for users.

**Describe the solution you'd like**

Research if we can use Firebase remote config for feature toggles, such as:
- FPS monitor
- hiding the user/password login feature
- display current renderer (HTML or skia)

**Additional information**
- https://firebase.google.com/docs/remote-config
- https://firebase.google.com/docs/remote-config/use-config-web
- https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config

We may be able to contribute web support to firebase_remote_config and send this upstream.

Launch Darkly explains why feature flags are useful.

> Feature flags enable development and operations teams to deploy code at any time, even if a feature isn't ready to be released to users. Wrapping code with feature flags gives you the safety to test new features and infrastructure in your production environments, without impacting the wrong end users.
>
> When you are ready to release more widely, simply update the flag status and the changes are made instantaneously.
>
> https://launchdarkly.com/

**Comment by illia-romanenko** [comment]
Considerations: 
- How deactivating Email/Password login option will affect security rules?
- How well firebase remote config supported in flutter for web?

**Comment by bootstraponline** [comment]
> * How deactivating Email/Password login option will affect security rules?

I think we'd keep the security rules the same. This is only about hiding the UI.

> * How well firebase remote config supported in flutter for web?

They have a full featured JS SDK, I think we can call into this from Dart (similar to the other FlutterFire SDKs). There's not currently an official dart wrapper.

**Comment by bootstraponline** [comment]
https://stackoverflow.com/questions/62781826/accessing-remoteconfig-create-loop-flutter-web looks like this might be possible?

**Comment by illia-romanenko** [comment]
@bootstraponline we need to try it out, thanks for sharing!
