### ISSUE TITLE
Navigator 2.0

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#641]
**Author the user story for this feature**

As a user, I want to make sure that we have extended navigator capabilities so I can have a more pleasing experience.

**Is your feature request related to a problem? Please describe.**
New Navigator 2.0 release.

**Describe the solution you'd like**
Use new Navigator 2.0 for all routing.

**Describe alternatives you've considered**
Using Navigator 1.0.

**Additional context**
https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f
https://medium.com/flutter/learning-flutters-new-navigation-and-routing-system-7c9068155ade

**Comment by illia-romanenko** [comment]
Discussion: we need to investigate it more to understand how well it fits the Metrics app, as we are currently customizing the Navigator (disable animations) and use it in tests so this might not actually give us many benefits. Suggestion to start with an investigation ticket (3 Tigers).

**Comment by bootstraponline** [comment]
https://docs.google.com/document/d/1Q0jx0l4-xymph9O6zLaOY4d_f7YFpNWX_eGbzYxr9wY/edit#heading=h.l6kdsrb6j9id

**Comment by illia-romanenko** [comment]
Dup of #911
