### ISSUE TITLE
Silent NPE: Add/Edit Project group

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#659]
**Describe the bug**
Silent NPE on closing Add/Edit project group dialog.

**To Reproduce**
1. Open Add project group dialog
2. Enter Project group name
3. Close dialog
4. Notice exception in the debug log

**Expected behavior**
No exception is thrown.

**Additional context**
════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following JSNoSuchMethodError was thrown while dispatching notifications for TextEditingController:
NoSuchMethodError: invalid member on null: 'selectedProjectIds'

When the exception was thrown, this was the stack: 
packages/metrics/project_groups/presentation/widgets/project_group_dialog.dart 252:60  [_updateActionButtonState]
packages/flutter/src/foundation/change_notifier.dart 209:21                            notifyListeners
packages/flutter/src/foundation/change_notifier.dart 276:5                             set value
packages/flutter/src/widgets/editable_text.dart 1653:23                                set [_value]
packages/flutter/src/widgets/editable_text.dart 2073:7                                 [_handleFocusChanged]
...
The TextEditingController sending notification was: TextEditingController#5cd3c(TextEditingValue(text: ┤ddfsf├, selection: TextSelection(baseOffset: -1, extentOffset: -1, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1)))
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by bootstraponline** [comment]
would a driver test be able to catch this issue?

**Comment by illia-romanenko** [comment]
@bootstraponline this issue is not reported in driver tests (and in Chrome console), I did a quick couple of tests to catch this but they never fail

**Comment by bootstraponline** [comment]
maybe sentry will catch this in the future once we set it up.
https://github.com/getsentry/sentry-dart/
