### ISSUE TITLE
Lock mobile browser users, but allow desktop version

### ISSUE THREAD

**Issue by illia-romanenko** [platform-platform/monorepo#825]
**Description**
As we don't have mobile layouts implemented we want to lock the mobile experience and display "Mobile browsers are not supported." message for all mobile users (if they choose to request desktop site - the message shouldn't be displayed).
From the UI perspective, it could be just centered text that looks good on the mobile.

**Acceptance Criteria**
- [ ] If the user is using a mobile browser -  "Mobile browsers are not supported." message is displayed
- [ ] If the user is using a mobile browser and requests a desktop site - the message is NOT displayed
- [ ] Works well with both themes

**Comment by bootstraponline** [comment]
@illia-romanenko I think we can skip this ticket. Mobile users try their luck with the existing support. I'll just be careful to message that we don't officially support mobile yet.
